-- ============================================================
-- WebShop v2.0 - Seed-data (20 tuotetta)
-- ============================================================

INSERT INTO webshop."Product" (title, description, price, category, "imageUrl", available, "inventoryCount", tags) VALUES

-- Vaporisaattorit & Tarvikkeet (5)
('PocketVape Mini — Taskukokoinen Höyrystin', 'Diskreetti taskukokoinen höyrystin kuivalle yrtille. Kolme lämpötila-asetusta, USB-C-lataus, haptinen palaute. Täydellinen aloittelijalle joka haluaa siirtyä savuttomaan elämään.', 89.99, 'Vaporisaattorit', 'https://images.unsplash.com/photo-1559564426-013b32d47136?w=600', TRUE, 34, ARRAY['höyrystin','taskukokoinen','usb-c','savuton']),
('CloudMaster 3000 — Pöytähöyrystin', 'Täydellinen kotihöyrystin jolla saat kaiken irti yrteistäsi. Tarkka digitaalinen lämpötilasäätö 1°C tarkkuudella. Hiljainen tuuletin, LED-tunnelmavalaistus. "Kylläpä on pehmeetä" — tyytyväinen asiakas.', 249.99, 'Vaporisaattorit', 'https://images.unsplash.com/photo-1585155967844-ebd6ee06f44a?w=600', TRUE, 12, ARRAY['pöytähöyrystin','tarkka','hiljainen','led']),
('HerbGrinder Deluxe — 4-kerroksinen Mylly', 'Premium-mylly terävillä timanttihampailla. 4 kerrosta: jauhatus, keräys, siivilä ja kief-kammio. Magneettikansi pysyy kiinni. Mukana puhdistussivellin ja kaavin.', 39.99, 'Vaporisaattorit', 'https://images.unsplash.com/photo-1603807008857-ad66b70431aa?w=600', TRUE, 67, ARRAY['mylly','4-kerroksinen','premium','magneetti']),
('HerbSaver UV — UV-suojattu Säilytyspurkki', 'UV-suojattu lasipurkki joka pitää yrtit tuoreina ja potentteina. Ilmatiivis tiiviste, sisäänrakennettu kosteusmittari. Kolme kokoa: S (5g), M (10g), L (30g).', 24.99, 'Vaporisaattorit', 'https://images.unsplash.com/photo-1615486511484-92e172cc4fe0?w=600', TRUE, 89, ARRAY['säilytys','uv-suoja','ilmatiivis','kosteusmittari']),
('CleanKit Pro — Puhdistussetti Höyrystimille', 'Täydellinen puhdistussetti: isopropyylialkoholipyyhkeitä, piippurasseja, puikkoja, pinsetit ja puhdistusharja. Säilytyskotelossa. "Puhdas höyrystin on iloinen höyrystin."', 19.99, 'Vaporisaattorit', 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=600', TRUE, 120, ARRAY['puhdistus','setti','huolto','tarvikkeet']),

-- Lasitaide & Säilytys (5)
('Rainbow Bowl — Käsinpuhallettu Lasikulho', 'Taiteilijan käsinpuhaltama lasikulho sateenkaaren väreissä. Jokainen kappale uniikki. Pakkauksessa mukana pehmustettu säilytyskotelo. Sopii myös hedelmäkulhoksi.', 59.99, 'Lasitaide', 'https://images.unsplash.com/photo-1576020798425-49a0ba4a0d7a?w=600', TRUE, 8, ARRAY['lasitaide','käsintehty','uniikki','värikäs']),
('Crystal Clear — Kristallinen Bongi', 'Tyylikäs minimalistinen bongi borosilikaattilasista. Helppo puhdistaa, irrotettava alaosa. Korkeus 30cm. Sisältää 14mm kukka-kupin.', 79.99, 'Lasitaide', 'https://images.unsplash.com/photo-1559732277-314a03f52b4f?w=600', TRUE, 15, ARRAY['bongi','kristalli','borosilikaatti','minimalistinen']),
('StashBox Large — Lukollinen Säilytyslaatikko', 'Tyylikäs bambuinen säilytyslaatikko numerolukolla. Sisältää lokerot yrteille, papereille, myllylle ja muille tarvikkeille. Hajuamaton — kämppis ei huomaa.', 44.99, 'Lasitaide', 'https://images.unsplash.com/photo-1602872030219-ad2b9a54315c?w=600', TRUE, 42, ARRAY['säilytys','lukollinen','bambu','hajuton']),
('PipeArt Collection — Koristeellinen Piippu', 'Käsinveistetty puupiippu monimutkaisilla kaiverruksilla. Tammipuuta, käsitelty mehiläisvahalla. Keräilykappale joka on myös toimiva.', 34.99, 'Lasitaide', 'https://images.unsplash.com/photo-1494389360671-0d6b4c3e8e4e?w=600', FALSE, 0, ARRAY['piippu','käsityö','puu','keräily']),
('SmellProof Bag XL — Hajutiivis Laukku', 'Aktiivihiilisuodattimella varustettu hajutiivis kantolaukku. Mahtuu kannettava höyrystin, mylly, purkki ja muut tarvikkeet. Ulospäin näyttää tavalliselta toilettilaukulta.', 29.99, 'Lasitaide', 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600', TRUE, 55, ARRAY['hajuton','laukku','aktiivihiili','kantolaukku']),

-- Hamppu-vaatteet (4)
('HamppuT-paita — Luomuhamppua', '100% luomuhamppua. Hengittävä, antibakteerinen ja kestävämpi kuin puuvilla. Pehmenee joka pesussa. "Käytä luontoa, älä muovia."', 34.99, 'Hamppuvaatteet', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600', TRUE, 48, ARRAY['hamppu','luomu','hengittävä','kestävä']),
('HempHoodie — Hamppukollari', 'Lämmin ja pehmeä hamppu-puuvillasekoitteinen huppari. Vahvistetut saumat, iso etutasku. Saatavilla luonnonvalkoisena ja vihreänä. "Niin mukava ettei tee mieli riisua."', 69.99, 'Hamppuvaatteet', 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600', TRUE, 27, ARRAY['huppari','hamppu','lämmin','mukava']),
('HempCap — Hamppulippis', 'Tyylikäs hamppukankainen lippis säädettävällä hihnalla. Hengittävä ja kevyt. Kirjailtu pieni hamppulehti sivussa — vain tarkkasilmäiset huomaavat.', 24.99, 'Hamppuvaatteet', 'https://images.unsplash.com/photo-1588850561407-ed78c282e36b?w=600', TRUE, 73, ARRAY['lippis','hamppu','kevyt','tyylikäs']),
('HempSocks 3-pack — Hamppusukat', 'Kolmen parin setti hamppusukkia. Lämpimät talvella, viileät kesällä. Luonnollinen antibakteerisuus pitää jalat raikkaina. "Jalat kiittää."', 14.99, 'Hamppuvaatteet', 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600', TRUE, 110, ARRAY['sukat','hamppu','setti','hengittävä']),

-- Hyvinvointi & CBD (3)
('CBD-öljy 10% — Full Spectrum', 'Korkealaatuinen täyden spektrin CBD-öljy hamppu-uutteesta. 10% (1000mg/10ml). Kolmannen osapuolen laboratoriotestattu. Ei sisällä THC:tä. "Rauhoittaa mielen ja kehon."', 49.99, 'Hyvinvointi', 'https://images.unsplash.com/photo-1611070960566-2c62c30b36b4?w=600', TRUE, 38, ARRAY['cbd','öljy','full-spectrum','lab-testattu']),
('CBD Salve 500mg — Lihasvoide', 'Viilentävä CBD-lihasvoide urheilun jälkeiseen palautumiseen. 500mg CBD:tä, mentolia ja arnikaa. "Kun jalat huutaa armoa, tämä vastaa."', 34.99, 'Hyvinvointi', 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600', TRUE, 52, ARRAY['cbd','voide','lihas','urheilu']),
('WellnessTea — Hampputee-sekoitus', 'Rentouttava yrttitee-sekoitus jossa hamppua, kamomillaa, laventelia ja sitruunamelissaa. 20 pussia. "Hengitä sisään teetä, hengitä ulos stressiä."', 9.99, 'Hyvinvointi', 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600', TRUE, 95, ARRAY['tee','hamppu','rentoutus','yrtti']),

-- Keittiö & Herkuttelu (3)
('MunchBox Premium — Herkkuboksi', 'Täydellinen herkkuboksi iltaan: käsintehtyä suklaata, pähkinöitä, kuivattuja hedelmiä ja keksejä. "Kun iskee nälkä, iskee kunnolla." Kauniissa lahjapakkauksessa.', 29.99, 'Herkkuboksi', 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=600', TRUE, 22, ARRAY['herkut','suklaa','lahja','ilta']),
('SnackMaster 2000 — Nachopelti', 'Jättikokoinen nachopelti: tortillasipsejä, cheddarjuustoa, jalapenoa, salsaa, smetanaa ja guacamolea. Pakasteesta uuniin, valmista 15 minuutissa. "Kun on pakko saada jotain hyvää."', 14.99, 'Herkkuboksi', 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=600', FALSE, 0, ARRAY['nachot','juusto','pikaruoka','uuni']),
('Cookie Jar — Jättikeksi 25cm', 'Yksi massiivinen 25cm suklaakeksi. Paistetaan uunissa ja jaetaan kavereiden kesken — tai ei. "Jaa kavereiden kesken" on vain ehdotus.', 19.99, 'Herkkuboksi', 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600', TRUE, 16, ARRAY['keksi','suklaa','jättikoko','jaettava']);
